# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for the DataLab desktop GUI.

All paths are derived from ``Path(__file__).resolve().parent`` so the
spec works on any clone, CI runner, or fresh checkout — no hard-coded
``/Users/...`` references that break a sibling tree or another
developer's machine. The spec is regenerated by PyInstaller on each
build, so do NOT edit by hand without verifying the regeneration
preserves the relative-path discipline (the build scripts pass
``--name DataLab`` so the generated spec name is stable).

Input scope (kept in sync with build_mac_data_gui.sh / build_windows_
data_gui.ps1):
- entry script: ``data_extrapolation_gui.py`` at the project root
- data assets: ``docs/desktop/`` (manuals) + ``shared/help_specs.json``
- icon: ``build/macos_gui_build/app_icon.icns`` (created by the
  build script before PyInstaller runs; absent on first invocation —
  guarded with ``Path.is_file()``)
- hidden imports + ``collect_all`` for mpmath, emcee, corner — these
  ship behind ``HAS_EMCEE`` runtime guards so PyInstaller's static
  analyser drops them without explicit declaration
"""
from pathlib import Path

from PyInstaller.utils.hooks import collect_all

# ``SPECPATH`` is set by PyInstaller when it executes a spec file; it
# points at the directory holding this file. Falling back to
# ``__file__`` keeps the spec runnable as a plain script for diffs +
# IDE static analysis.
PROJECT_ROOT = Path(globals().get("SPECPATH") or Path(__file__).resolve().parent)


def _rel(*parts: str) -> str:
    """Return an absolute path under the project root, as a string.

    PyInstaller's API takes strings, not Path objects, in the
    ``datas`` / ``Analysis(scripts=...)`` slots; ``str()`` here keeps
    the spec readable while still anchoring every path to the root.
    """
    return str(PROJECT_ROOT.joinpath(*parts))


datas = [
    (_rel("pyproject.toml"), "."),
    (_rel("DataLab.png"), "."),
    (_rel("docs", "desktop"), "docs/desktop"),
    (_rel("shared", "help_specs.json"), "shared"),
]
binaries = []
hiddenimports = [
    "mpmath",
    "emcee",
    "emcee.moves",
    "emcee.backends",
    "corner",
]
for _pkg in ("mpmath", "emcee", "corner"):
    _d, _b, _h = collect_all(_pkg)
    datas += _d
    binaries += _b
    hiddenimports += _h


# Icon is generated by the build script before PyInstaller runs; if
# absent (e.g. running the spec from a clean clone for diff/CI), pass
# ``None`` so PyInstaller falls back to its default rather than
# erroring on a missing path.
_icon_path = Path(_rel("build", "macos_gui_build", "app_icon.icns"))
ICON = str(_icon_path) if _icon_path.is_file() else None


a = Analysis(
    [_rel("data_extrapolation_gui.py")],
    pathex=[str(PROJECT_ROOT)],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        # Heavy Qt sub-modules DataLab never touches. Keeps the .app
        # under 200 MB. See ``build_mac_data_gui.sh`` for the
        # canonical list — when adding a new exclude, mirror it
        # there too.
        "PySide6.Qt3DAnimation", "PySide6.Qt3DCore", "PySide6.Qt3DExtras",
        "PySide6.Qt3DInput", "PySide6.Qt3DLogic", "PySide6.Qt3DRender",
        "PySide6.QtAsyncio", "PySide6.QtBluetooth", "PySide6.QtCharts",
        "PySide6.QtConcurrent", "PySide6.QtDataVisualization",
        "PySide6.QtDesigner", "PySide6.QtGraphs", "PySide6.QtGraphsWidgets",
        "PySide6.QtHelp", "PySide6.QtHttpServer", "PySide6.QtLocation",
        "PySide6.QtMultimedia", "PySide6.QtMultimediaWidgets",
        "PySide6.QtNetworkAuth", "PySide6.QtNfc", "PySide6.QtOpenGL",
        "PySide6.QtOpenGLWidgets", "PySide6.QtPdf", "PySide6.QtPdfWidgets",
        "PySide6.QtPositioning", "PySide6.QtQuick", "PySide6.QtQuick3D",
        "PySide6.QtQuickControls2", "PySide6.QtQuickTest",
        "PySide6.QtQuickWidgets", "PySide6.QtRemoteObjects",
        "PySide6.QtScxml", "PySide6.QtSensors", "PySide6.QtSerialBus",
        "PySide6.QtSerialPort", "PySide6.QtSpatialAudio", "PySide6.QtSql",
        "PySide6.QtStateMachine", "PySide6.QtSvg", "PySide6.QtSvgWidgets",
        "PySide6.QtTest", "PySide6.QtTextToSpeech", "PySide6.QtUiTools",
        "PySide6.QtWebChannel", "PySide6.QtWebEngineCore",
        "PySide6.QtWebEngineQuick", "PySide6.QtWebEngineWidgets",
        "PySide6.QtWebSockets", "PySide6.QtWebView", "PySide6.QtXml",
        "PySide6.scripts", "PySide6.support",
    ],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="DataLab",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=[ICON] if ICON else None,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name="DataLab",
)
app = BUNDLE(
    coll,
    name="DataLab.app",
    icon=ICON,
    bundle_identifier=None,
)
