"""Jupyter Notebook export.

Builds an nbformat-4-valid ``.ipynb`` dict that contains:
- A markdown summary cell (title + parameters + model label)
- A code cell that reproduces the fit using DataLab's public Python
  API (so the notebook is reproducible offline — the user can re-run
  the cell and get the same parameters)
- Optionally a plot cell that renders data + fit via matplotlib

No ``nbformat`` dependency — we emit the JSON structure directly.
This keeps the install footprint thin (nbformat is ~30 MB of
transitive deps including jsonschema) and lets the CLI stay headless.
If nbformat IS installed, the test suite uses it for authoritative
structural validation.

Placed under ``datalab_latex/`` alongside the LaTeX export because
it serves the same user workflow — "take this fit somewhere else" —
and shares the parameter-substitution utilities.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Iterable, Mapping

__all__ = ["build_notebook", "write_notebook"]


def _markdown_summary(
    title: str,
    model_label: str,
    params: Mapping[str, float],
    n_points: int,
) -> list[str]:
    """Lines of markdown for the summary cell. Returned as a list so
    the nbformat spec's ``source`` field is idiomatic (one list
    element per line; the newline is implicit)."""
    lines = [
        f"# {title}\n",
        "\n",
        "This notebook was auto-generated by **DataLab** from a fit result.\n",
        "\n",
        f"- Model: `{model_label}`\n",
        f"- Data points: {n_points}\n",
        "\n",
        "## Fitted parameters\n",
        "\n",
        "| Name | Value |\n",
        "| --- | --- |\n",
    ]
    for name, value in params.items():
        lines.append(f"| `{name}` | `{float(value):.6g}` |\n")
    lines.append("\n")
    lines.append(
        "Re-run the code cell below to reproduce the fit with DataLab's "
        "public API. Edit ``xs`` / ``ys`` to apply the same model to "
        "new data.\n"
    )
    return lines


def _code_reproduce_fit(
    xs: list[float],
    ys: list[float],
    model_id: str,
    params: Mapping[str, float],
) -> list[str]:
    """Lines of Python that refit the data. Uses DataLab's public API
    (``fitting.auto_models.fit_linear_model``) so the notebook stays
    reproducible without any private API dependencies.

    ``model_id`` should be the engine's identifier (``M1``, ``M2``, …).
    If the caller passed a friendly alias (``"linear"``), the code cell
    maps it to the identifier before looking it up — matches the CLI's
    alias handling.
    """
    params_repr = ", ".join(f"{k!r}: {float(v):.12g}" for k, v in params.items())
    return [
        "# Reproducible DataLab fit\n",
        "from fitting.auto_models import AUTO_MODELS, fit_linear_model\n",
        "from shared.precision import precision_guard\n",
        "\n",
        f"xs = {xs!r}\n",
        f"ys = {ys!r}\n",
        f"model_id = {model_id!r}\n",
        "expected_params = {" + params_repr + "}\n",
        "\n",
        "by_id = {d.identifier: d for d in AUTO_MODELS}\n",
        "alias = {'linear': 'M1', 'quadratic': 'M2', 'cubic': 'M3',\n",
        "         'log': 'M4', 'inverse': 'M5', 'exponential': 'M7'}\n",
        "definition = by_id[alias.get(model_id.lower(), model_id)]\n",
        "\n",
        "with precision_guard(50):\n",
        "    result = fit_linear_model(definition, xs, ys, precision=50)\n",
        "print(result.params)\n",
    ]


def _code_plot(xs: list[float], ys: list[float]) -> list[str]:
    return [
        "# Quick plot — data + fit preview\n",
        "import matplotlib\n",
        'matplotlib.use("Agg")  # headless-safe; drop if running interactively\n',
        "import matplotlib.pyplot as plt\n",
        "\n",
        f"xs = {xs!r}\n",
        f"ys = {ys!r}\n",
        "\n",
        "plt.figure(figsize=(8, 5))\n",
        'plt.scatter(xs, ys, label="data")\n',
        'plt.xlabel("x"); plt.ylabel("y"); plt.legend()\n',
        'plt.title("DataLab fit preview")\n',
        'plt.grid(True, alpha=0.3)\n',
        "plt.show()\n",
    ]


def _code_cell(source: list[str]) -> dict:
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": source,
    }


def _markdown_cell(source: list[str]) -> dict:
    return {
        "cell_type": "markdown",
        "metadata": {},
        "source": source,
    }


def build_notebook(
    title: str,
    xs: Iterable[float],
    ys: Iterable[float],
    model_label: str,
    params: Mapping[str, float],
    include_plot: bool = False,
) -> dict:
    """Build an nbformat-4 dict for a DataLab fit.

    Parameters
    ----------
    title: markdown H1 title
    xs, ys: parallel numeric sequences (must have equal length)
    model_label: human-readable or identifier (both accepted)
    params: {param_name: value}
    include_plot: if True, append a code cell with a matplotlib quick plot
    """
    xs_list = [float(v) for v in xs]
    ys_list = [float(v) for v in ys]
    if not xs_list or not ys_list:
        raise ValueError("notebook export requires non-empty xs and ys")
    if len(xs_list) != len(ys_list):
        raise ValueError(
            f"xs ({len(xs_list)}) and ys ({len(ys_list)}) must have the same length"
        )

    cells = [
        _markdown_cell(_markdown_summary(title, model_label, params, len(xs_list))),
        _code_cell(_code_reproduce_fit(xs_list, ys_list, model_label, params)),
    ]
    if include_plot:
        cells.append(_code_cell(_code_plot(xs_list, ys_list)))

    return {
        "nbformat": 4,
        "nbformat_minor": 5,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
            "language_info": {
                "name": "python",
                "version": "3",
                "pygments_lexer": "ipython3",
            },
            "datalab": {
                "exported_by": "DataLab",
                "generator_version": "Phase 3 #11",
            },
        },
        "cells": cells,
    }


def write_notebook(notebook: dict, path: Path) -> None:
    """Write an nbformat-4 dict to disk as a ``.ipynb`` file."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(notebook, indent=1, ensure_ascii=False),
        encoding="utf-8",
    )
